import express, { Request, Response } from 'express';
import db from '../../../lib/db';

const router = express.Router();

// Local ticket result type (mirrors backend DB export)
interface TicketQueryResult {
    train_code: string;
    from_station: string;
    to_station: string;
    departure_time: string;
    arrival_time: string;
    duration: string;
    business_seat: {
        price: number;
        available: number;
    };
    first_class: {
        price: number;
        available: number;
    };
    second_class: {
        price: number;
        available: number;
    };
}

let mockTickets: TicketQueryResult[] = [];

/**
 * GET /api/v1/tickets/query
 * 查询车票信息
 * Query Parameters:
 * - from: 出发站(必填)
 * - to: 到达站(必填)
 * - date: 出发日期 YYYY-MM-DD(必填)
 * - train_type: 车次类型(可选, G/D/K等)
 */
router.get('/query', async (req: Request, res: Response) => {
    const { from, to, date, train_type } = req.query;

    // 参数验证
    if (!from || !to || !date) {
        return res.status(400).json({
            code: 1,
            message: '出发站、到达站和日期为必填参数',
            data: null,
        });
    }

    // 日期格式验证
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    if (!dateRegex.test(date as string)) {
        return res.status(400).json({
            code: 1,
            message: '日期格式错误，应为YYYY-MM-DD',
            data: null,
        });
    }

    try {
        const tickets = await db.queryTickets(from as string, to as string, date as string, train_type as string | undefined);

        return res.json({
            code: 0,
            message: '查询成功',
            data: {
                tickets,
                query_date: date,
            },
        });
    } catch (err) {
        console.error('tickets query failed', err);
        return res.status(500).json({ code: 2, message: '查询失败', data: null });
    }
});

// 测试辅助函数 - 仅用于测试环境
// For tests: allow overriding DB content by clearing and adding provided tickets
export async function setMockTickets(tickets: TicketQueryResult[]) {
    // convert TicketQueryResult -> ScheduleRecord-like object used by db
    // Keep ids autogenerated as train_code + index
    const recs = tickets.map((t, idx) => ({
        id: `${t.train_code}-${idx}`,
        train_code: t.train_code,
        from_station: t.from_station,
        to_station: t.to_station,
        departure_time: t.departure_time,
        arrival_time: t.arrival_time,
        duration_minutes: 0,
        business_price: t.business_seat.price,
        first_price: t.first_class.price,
        second_price: t.second_class.price,
        business_available: t.business_seat.available,
        first_available: t.first_class.available,
        second_available: t.second_class.available,
    }))

    // clear + add
    // @ts-ignore - db has clear/addSchedule
    if (typeof (db as any).clear === 'function') {
        // @ts-ignore
        await (db as any).clear()
    }
    for (const r of recs) {
        // @ts-ignore
        await (db as any).addSchedule(r)
    }
}

export async function clearMockTickets() {
    if (typeof (db as any).clear === 'function') {
        // @ts-ignore
        await (db as any).clear()
    }
}

/**
 * POST /api/v1/tickets/book
 * Body: { train_code, from, to, date, seat_type, passenger_name, passenger_id }
 */
router.post('/book', async (req: Request, res: Response) => {
    const { train_code, from, to, date, seat_type, passenger_name, passenger_id } = req.body || {}

    if (!train_code || !from || !to || !date || !seat_type || !passenger_name) {
        return res.status(400).json({ code: 1, message: '缺少必填字段', data: null })
    }

    if (!['business', 'first', 'second'].includes(seat_type)) {
        return res.status(400).json({ code: 1, message: 'seat_type 必须为 business|first|second', data: null })
    }

    try {
        // create order record (this reserves seat and persists both availability and order)
        // @ts-ignore
        const order = await (db as any).createOrder({
            train_code,
            from,
            to,
            date,
            seat_type,
            passenger_name,
            passenger_id,
        })

        return res.json({
            code: 0,
            message: '预订成功',
            data: order,
        })
    } catch (err: any) {
        console.error('booking failed', err)
        return res.status(500).json({ code: 2, message: err.message || '预订失败', data: null })
    }
})

// Orders endpoints
router.get('/orders/:order_id', async (req: Request, res: Response) => {
    const { order_id } = req.params
    try {
        // @ts-ignore
        const ord = await (db as any).getOrder(order_id)
        if (!ord) return res.status(404).json({ code: 1, message: '未找到订单', data: null })
        return res.json({ code: 0, message: 'ok', data: ord })
    } catch (err: any) {
        return res.status(500).json({ code: 2, message: err.message || '查询失败', data: null })
    }
})

router.get('/orders', async (req: Request, res: Response) => {
    const { passenger_name } = req.query
    try {
        // @ts-ignore
        const list = await (db as any).listOrders({ passenger_name: passenger_name as string | undefined })
        return res.json({ code: 0, message: 'ok', data: list })
    } catch (err: any) {
        return res.status(500).json({ code: 2, message: err.message || '查询失败', data: null })
    }
})

router.post('/orders/:order_id/cancel', async (req: Request, res: Response) => {
    const { order_id } = req.params
    try {
        // @ts-ignore
        const ord = await (db as any).cancelOrder(order_id)
        return res.json({ code: 0, message: '取消成功', data: ord })
    } catch (err: any) {
        return res.status(400).json({ code: 1, message: err.message || '取消失败', data: null })
    }
})

export default router;
